name = "Feature Lead Bridge"
client_id = "043415e66e7e5406b59601709dba928f"
application_url = "https://cooperandkid-feature-lead.vercel.app/"
embedded = false

[access_scopes]
scopes = "write_draft_orders,read_draft_orders,read_customers,write_customers"
use_legacy_install_flow = false

[app_proxy]
url = "https://feature-lead-bridge.vercel.app/api/feature-lead"
subpath = "feature-lead"
prefix = "apps"

[webhooks]
api_version = "2026-04"

[auth]
redirect_urls = [
  "https://feature-lead-bridge.vercel.app/api/auth/callback"
]

[pos]
embedded = false